export const SHOW_LIST_REQUEST = 'SHOW_LIST_REQUEST';
export const SHOW_LIST_SUCCESS = 'SHOW_LIST_SUCCESS';
export const SHOW_LIST_FAIL = 'SHOW_LIST_FAIL';

export const EPISODES_LIST_REQUEST = 'EPISODES_LIST_REQUEST';
export const EPISODES_LIST_SUCCESS = 'EPISODE_LIST_SUCCESS';
export const EPISODES_LIST_FAIL = 'EPISODE_LIST_FAIL';

export const EPISODE_DETAILS_REQUEST = 'EPISODE_DETAILS_REQUEST';
export const EPISODE_DETAILS_SUCCESS = 'EPISODE_DETAILS_SUCCESS';
export const EPISODE_DETAILS_FAIL = 'EPISODE_DETAILS_FAIL';
