export const SHOW_LIST_SUCCESS = 'SHOW_LIST_SUCCESS';
export const SHOW_LIST_FAIL = 'SHOW_LIST_FAIL';

export const EPISODES_LIST_SUCCESS = 'EPISODE_LIST_SUCCESS';
export const EPISODES_LIST_FAIL = 'EPISODE_LIST_FAIL';

export const EPISODE_DETAILS_SUCCESS = 'EPISODE_DETAILS_SUCCESS';
export const EPISODE_DETAILS_FAIL = 'EPISODE_DETAILS_FAIL';
